/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-12-05 03:49:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/../_inc/inc_head.jsp", Long.valueOf(1666591812734L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

AdminInfo loginInfo = (AdminInfo)session.getAttribute("loginInfo");
if (loginInfo == null) {
	out.println("<script> alert('잘못된 경로로 들어왔습니다.'); location.replace('admin_login.jsp'); </script>");
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Cworld_admin</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/cworldSite/img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<link rel=\"icon\" href=\"/cworldSite/img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/cworld_admin/js/jquery-3.6.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function onlyNum(obj) {\r\n");
      out.write("	if (isNaN(obj.value)) {\r\n");
      out.write("		obj.value = \"\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function startTimer(duration, display) {\r\n");
      out.write("  var timer = duration, minutes, seconds;\r\n");
      out.write("  var interval = setInterval(function () {\r\n");
      out.write("    minutes = parseInt(timer / 60, 10)\r\n");
      out.write("    seconds = parseInt(timer % 60, 10);\r\n");
      out.write("\r\n");
      out.write("    minutes = minutes < 10 ? \"0\" + minutes : minutes;\r\n");
      out.write("    seconds = seconds < 10 ? \"0\" + seconds : seconds;\r\n");
      out.write("\r\n");
      out.write("    display.textContent = minutes + \":\" + seconds;\r\n");
      out.write("\r\n");
      out.write("    if (--timer < 0) {\r\n");
      out.write("      timer = duration;\r\n");
      out.write("    }\r\n");
      out.write("    if(timer === 0) {\r\n");
      out.write("      clearInterval(interval);\r\n");
      out.write("      display.textContent = \"세션 만료!\";\r\n");
      out.write("    }\r\n");
      out.write("  }, 1000);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.onload = function () {\r\n");
      out.write("  /* 기본값 10(분)입니다. */\r\n");
      out.write("  var minutes = 10;\r\n");
      out.write("\r\n");
      out.write("  var fiveMinutes = (60 * minutes) - 1,\r\n");
      out.write("    display = document.querySelector('#MyTimer');\r\n");
      out.write("  startTimer(fiveMinutes, display);\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.contentDiv { width:80%; float:right; }\r\n");
      out.write("	body, th, td, div, p { font-size:1em; }\r\n");
      out.write("	body { \r\n");
      out.write("		background:#fff;\r\n");
      out.write("	}\r\n");
      out.write("	li, ul, ol { list-style-type:none; }\r\n");
      out.write("	#sideMenu a:link { text-decoration:none; color:#fff; }\r\n");
      out.write("	#sideMenu a:visited { text-decoration:none; color:#fff; }\r\n");
      out.write("	#sideMenu a:hover { text-decoration:underline; color:#fff; }\r\n");
      out.write("	#sideMenu a:active { text-decoration:none; color:#fff; }	\r\n");
      out.write("	.hand { cursor:pointer; }\r\n");
      out.write("	.bold { font-weight:bold; }\r\n");
      out.write("	#bigMenu1 { position:relative; top:20px; left:25px; display:block; }\r\n");
      out.write("	#bigMenu2 { position:relative; top:20px; left:25px; display:block; }\r\n");
      out.write("	#bigMenu3 { position:relative; top:20px; left:25px; display:block; }\r\n");
      out.write("	#bigMenu4 { position:relative; top:20px; left:25px; display:block; }\r\n");
      out.write("	\r\n");
      out.write("	#sideMenu { \r\n");
      out.write("		width:200px; height:100%; position:fixed; top:0; left:0px;\r\n");
      out.write("		background:rgba(100, 100, 100, 0.8); \r\n");
      out.write("	}\r\n");
      out.write("	#subnavi01 { width:200px; position:relative; top:20px; left:0px; display:none; text-align:center; }\r\n");
      out.write("	#subnavi02 { width:200px; position:relative; top:20px; left:0px; display:none; text-align:center; }\r\n");
      out.write("	#subnavi03 { width:200px; position:relative; top:20px; left:0px; display:none; text-align:center; }\r\n");
      out.write("	#subnavi04 { width:200px; position:relative; top:20px; left:0px; display:none; text-align:center; }\r\n");
      out.write("	#menus { width:200px; height:100%; }\r\n");
      out.write("	#loginInfo { position:absolute; margin:5px; top:10px; right:10px; text-align:right; }\r\n");
      out.write("	#logoutBtn { width:70px; margin-top:3px; }\r\n");
      out.write(".title { text-align:left; }\r\n");
      out.write("canvas {\r\n");
      out.write("	-moz-user-select: none;\r\n");
      out.write("	-webkit-user-select: none;\r\n");
      out.write("	-ms-user-select: none;\r\n");
      out.write("}\r\n");
      out.write(".hand { cursor:pointer; }\r\n");
      out.write(".resetSch { background-color:pink; border:pink; }\r\n");
      out.write("#footerBlank { position:absolute; top:150%; width:100px;  }\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"/cworld_admin/js/jquery-3.6.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("	$(\"#bigMenu1\").click(function() {\r\n");
      out.write("		$(\"#subnavi01\").slideToggle();\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#bigMenu2\").click(function() {\r\n");
      out.write("		$(\"#subnavi02\").slideToggle();\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#bigMenu3\").click(function() {\r\n");
      out.write("		$(\"#subnavi03\").slideToggle();\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#bigMenu4\").click(function() {\r\n");
      out.write("		$(\"#subnavi04\").slideToggle();\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("function logout() {\r\n");
      out.write("	if (confirm(\"로그아웃 하시겠습니까?\")) {\r\n");
      out.write("		location.href = \"/cworld_admin/logout.jsp\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"/cworld_admin/js/Chart.min.js\"></script>\r\n");
      out.write("<script src=\"/cworld_admin/js/utils.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"loginInfo\">\r\n");
      out.write("<b>");
      out.print(loginInfo.getAi_name() );
      out.write("</b> 님 환영합니다.<br />\r\n");
      out.write("<span id=\"MyTimer\">10:00</span>&nbsp;&nbsp;<input type=\"button\" value=\"로그아웃\" name=\"logout\" id=\"logoutBtn\" onclick=\"logout()\" />\r\n");
      out.write("</div>\r\n");
      out.write("<br /><br /><br />\r\n");
      out.write("<hr />\r\n");
      out.write("<div id=\"sideMenu\">\r\n");
      out.write("<a href=\"/cworld_admin/index.jsp\"><img src=\"/cworld_admin/img/cworld_logo.jpg\" width=\"200\" height=\"200\" /></a>\r\n");
      out.write("	<div id=\"menus\">\r\n");
      out.write("		<img src=\"/cworld_admin/img/ico_menu01.png\" width=\"150\" height=\"43\" id=\"bigMenu1\" />\r\n");
      out.write("		<div id=\"subnavi01\">\r\n");
      out.write("			<a href=\"/cworld_admin/product_in\">상품 등록</a><br />\r\n");
      out.write("			<a href=\"/cworld_admin/product_list\">상품 목록</a><br />\r\n");
      out.write("			<a href=\"/cworld_admin/product_list_stock\">재고 관리</a><br />\r\n");
      out.write("			<a href=\"/cworld_admin/rent_list\">대여 물품 관리</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<img src=\"/cworld_admin/img/ico_menu02.png\" width=\"150\" height=\"43\" id=\"bigMenu2\" />\r\n");
      out.write("		<div id=\"subnavi02\">\r\n");
      out.write("				<a href=\"/cworld_admin/member_list\">회원 목록</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/member_last\">장기 미접속 회원</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/member_exit\">탈퇴 회원관리</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/member_order_list\">결제 내역 관리</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<img src=\"/cworld_admin/img/ico_menu03.png\" width=\"150\" height=\"43\" id=\"bigMenu3\" />\r\n");
      out.write("		<div id=\"subnavi03\">\r\n");
      out.write("				<a href=\"/cworld_admin/notice_list\">공지 사항</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/qna_list\">1:1 문의</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/review_list\">리뷰</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/g_qna_list\">단체 문의</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/g_review_list\">단체 후기</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<img src=\"/cworld_admin/img/ico_menu04.png\" width=\"150\" height=\"43\" id=\"bigMenu4\" />\r\n");
      out.write("		<div id=\"subnavi04\">\r\n");
      out.write("				<a href=\"/cworld_admin/sta_home\">통계 홈</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/sta_month_sale\">연간 월별 판매량</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/sta_day_of_week\">요일별 판매량</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/sta_review\">판매량 대비 리뷰 개수</a><br />\r\n");
      out.write("				<a href=\"/cworld_admin/sta_amount\">분류별 판매량</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footerBlank\">\r\n");
      out.write("<br/><br/><br/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("#indexMenu th { border-bottom:1px solid black; }\r\n");
      out.write("#indexMenu a { text-decoration:none; color:black; }\r\n");
      out.write("#indexMenu a:link { text-decoration:none; color:black; }\r\n");
      out.write("#indexMenu a:visited { text-decoration:none; color:black; }\r\n");
      out.write("#indexMenu a:hover { text-decoration:underline; color:black; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"800\" height=\"300\" align=\"center\" id=\"indexMenu\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("<caption style=\"text-align:left; font-size:25px; font-weight:bold;\">메 뉴</caption>\r\n");
      out.write("<tr><th width=\"25%\">상품관리</th><th width=\"25%\">회원관리</th><th width=\"25%\">게시판관리</th><th width=\"25%\">통계관리</th></tr>\r\n");
      out.write("<tr align=\"center\">\r\n");
      out.write("<td>\r\n");
      out.write("<a href=\"product_in\">상품 등록</a><br /><br />\r\n");
      out.write("<a href=\"product_list\">상품 목록</a><br /><br />\r\n");
      out.write("<a href=\"product_list_stock\">재고 관리</a><br /><br />\r\n");
      out.write("<a href=\"rent_list\">대 여 물 품 관 리</a>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<a href=\"member_list\">회원 목록</a><br /><br />\r\n");
      out.write("<a href=\"member_last\">장기 미접속 회원</a><br /><br />\r\n");
      out.write("<a href=\"member_exit\">탈퇴 회원관리</a><br /><br />\r\n");
      out.write("<a href=\"member_order_list\">결제 내역 관리</a>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<a href=\"notice_list\">공지 사항</a><br /><br />\r\n");
      out.write("<a href=\"qna_list\">1:1 문의</a><br /><br />\r\n");
      out.write("<a href=\"review_list\">리뷰</a><br /><br />\r\n");
      out.write("<a href=\"g_qna_list\">단체 문의</a><br /><br />\r\n");
      out.write("<a href=\"g_review_list\">단체 후기</a>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<a href=\"/cworld_admin/sta_home\">통계 홈</a><br /><br />\r\n");
      out.write("<a href=\"/cworld_admin/sta_month_sale\">연간 월별 판매량</a><br /><br />\r\n");
      out.write("<a href=\"/cworld_admin/sta_day_of_week\">요일별 판매량</a><br /><br />\r\n");
      out.write("<a href=\"/cworld_admin/sta_review\">판매량 대비 리뷰 개수</a><br /><br />\r\n");
      out.write("<a href=\"/cworld_admin/sta_amount\">분류별 판매량</a>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
